import { resolve, dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { watch } from "node:fs/promises";
import { defineCommand } from "citty";
import {
  parseConfig,
  logger,
  TsqxError,
  generateMigrations,
  generateSchemaFiles,
  parseQueryFiles,
  type Config,
} from "@tsqx/core";

function runGenerate(config: Config, configDir: string) {
  const schemaPath = resolve(configDir, config.schema);
  const queriesPath = resolve(configDir, config.queries);
  const migrationsPath = resolve(configDir, config.migrations);

  // Validate schema directory
  if (!existsSync(schemaPath)) {
    logger.error(`Schema directory not found: ${schemaPath}`);
    return false;
  }
  if (readdirSync(schemaPath).filter((f) => f.endsWith(".sql")).length === 0) {
    logger.error(`No .sql files in schema directory: ${schemaPath}`);
    return false;
  }

  // Validate queries directory
  if (!existsSync(queriesPath)) {
    logger.error(`Queries directory not found: ${queriesPath}`);
    return false;
  }

  // Create migrations directory if needed
  if (!existsSync(migrationsPath)) {
    mkdirSync(migrationsPath, { recursive: true });
  }

  // Generate migrations
  const result = generateMigrations({
    schemaDir: schemaPath,
    migrationsDir: migrationsPath,
    dialect: config.dialect,
  });

  if (result.isErr()) {
    logger.error(result.error.message);
    return false;
  }

  const { migrationFile, operations, snapshot } = result.value;

  if (migrationFile) {
    logger.success(`Migration generated: ${migrationFile}`);
    for (const op of operations) {
      switch (op.type) {
        case "create_table":
          logger.step(`+ CREATE TABLE ${op.table.name}`);
          break;
        case "drop_table":
          logger.step(`- DROP TABLE ${op.tableName}`);
          break;
        case "add_column":
          logger.step(`+ ADD COLUMN ${op.tableName}.${op.column.name}`);
          break;
        case "drop_column":
          logger.step(`- DROP COLUMN ${op.tableName}.${op.columnName}`);
          break;
        case "alter_column":
          logger.step(`~ ALTER COLUMN ${op.tableName}.${op.columnName}`);
          break;
      }
    }
  } else {
    logger.info("No schema changes detected");
  }

  // Generate schema files (TypeScript types + JSON Schema per table)
  const outDir = join(configDir, "generated");
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const schemaFiles = generateSchemaFiles(snapshot, config.dialect);
  for (const [filename, content] of Object.entries(schemaFiles)) {
    writeFileSync(join(outDir, filename), content, "utf-8");
  }

  logger.success(`Schema files generated: ${outDir}`);
  for (const filename of Object.keys(schemaFiles)) {
    logger.step(filename);
  }

  // Generate query functions
  const queryFiles = readdirSync(queriesPath).filter((f) => f.endsWith(".sql"));
  if (queryFiles.length > 0) {
    const queryContents = queryFiles.map((f) => ({
      filename: f,
      content: readFileSync(join(queriesPath, f), "utf-8"),
    }));

    const queryResult = parseQueryFiles(queryContents, snapshot);
    if (queryResult.isErr()) {
      logger.error(queryResult.error.message);
      return false;
    }

    const queries = queryResult.value;
    if (queries.length > 0) {
      const genDir = join(queriesPath, "gen");
      if (!existsSync(genDir)) {
        mkdirSync(genDir, { recursive: true });
      }

      const queryCodeFiles = config.dialect.generateQueryCode(queries, snapshot);
      for (const [filename, content] of Object.entries(queryCodeFiles)) {
        writeFileSync(join(genDir, filename), content, "utf-8");
      }

      // Write barrel index.ts in queries/ (not gen/)
      const barrelLines = [
        "// This file is auto-generated by tsqx. Do not edit manually.",
        "",
      ];
      for (const filename of Object.keys(queryCodeFiles)) {
        const basename = filename.replace(/\.ts$/, "");
        barrelLines.push(`export * from "./gen/${basename}";`);
      }
      barrelLines.push("");
      writeFileSync(join(queriesPath, "index.ts"), barrelLines.join("\n"), "utf-8");

      logger.success(`Query functions generated: ${genDir}`);
      logger.step("index.ts");
      for (const filename of Object.keys(queryCodeFiles)) {
        logger.step(`gen/${filename}`);
      }
    }
  }

  return true;
}

export const generate = defineCommand({
  meta: {
    name: "generate",
    description: "Generate type-safe SQL queries",
  },
  args: {
    config: {
      type: "string",
      alias: "c",
      description: "Path to tsqx config file",
      default: "./src/db/tsqx.config.ts",
    },
    watch: {
      type: "boolean",
      alias: "w",
      description: "Watch for changes and regenerate",
      default: false,
    },
  },
  async run({ args }) {
    const configPath = resolve(process.cwd(), args.config);
    logger.debug(`Loading config from ${configPath}`);

    let config: Config;
    try {
      const mod = await import(pathToFileURL(configPath).href);
      const raw = mod.default ?? mod;

      const result = parseConfig(raw);

      if (result.isErr()) {
        logger.error(result.error.message);
        process.exit(1);
      }

      config = result.value;
    } catch (e) {
      if (e instanceof TsqxError) {
        logger.error(e.message);
      } else {
        logger.error(
          `Failed to load config: ${e instanceof Error ? e.message : e}`,
        );
      }
      process.exit(1);
    }

    const configDir = dirname(configPath);
    const schemaPath = resolve(configDir, config.schema);
    const queriesPath = resolve(configDir, config.queries);

    logger.success("Config loaded successfully");
    logger.step(`schema: ${schemaPath}`);
    logger.step(`queries: ${queriesPath}`);
    logger.step(`migrations: ${resolve(configDir, config.migrations)}`);

    // Initial generate
    const ok = runGenerate(config, configDir);
    if (!ok && !args.watch) {
      process.exit(1);
    }

    if (!args.watch) return;

    // Watch mode
    logger.info("Watching for changes...");

    let debounceTimer: ReturnType<typeof setTimeout> | null = null;

    const regenerate = () => {
      if (debounceTimer) clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        logger.info("Change detected, regenerating...");
        console.log("");
        runGenerate(config, configDir);
        logger.info("Watching for changes...");
      }, 100);
    };

    const watchDir = async (dir: string) => {
      try {
        for await (const event of watch(dir, { recursive: true })) {
          if (event.filename?.endsWith(".sql")) {
            regenerate();
          }
        }
      } catch {
        // Directory might not exist yet, ignore
      }
    };

    // Watch schema and queries directories
    watchDir(schemaPath);
    watchDir(queriesPath);
  },
});
