import { pascalCase, type SchemaSnapshot } from "@tsqx/core";
import type { QueryDef, QueryCommand } from "@tsqx/core";
import { sqlTypeToJsonSchema, sqlTypeToTsType } from "./types";

function camelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function generateParamInterface(query: QueryDef): string | null {
  if (query.params.length === 0) return null;

  const name = `${pascalCase(query.name)}Params`;
  const fields = query.params
    .map((p) => `  ${p.name}: ${sqlTypeToTsType(p.sqlType)};`)
    .join("\n");

  return `export interface ${name} {\n${fields}\n}`;
}

function generateParamSchema(query: QueryDef): string | null {
  if (query.params.length === 0) return null;

  const name = `${pascalCase(query.name)}ParamsSchema`;
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const param of query.params) {
    properties[param.name] = sqlTypeToJsonSchema(param.sqlType);
    required.push(param.name);
  }

  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: `${pascalCase(query.name)}Params`,
    type: "object",
    properties,
    required,
    additionalProperties: false,
  };

  return `export const ${name} = ${JSON.stringify(schema, null, 2)} as const;`;
}

function generateResultType(query: QueryDef, snapshot: SchemaSnapshot): string | null {
  if (query.command === "exec" || query.command === "execrows" || query.command === "execresult") {
    return null;
  }

  if (!query.returnsTable || !snapshot[query.returnsTable]) return null;

  const table = snapshot[query.returnsTable];
  const typeName = pascalCase(query.returnsTable);

  // If returning all columns, just re-export the table type
  if (
    query.returnsColumns.length === table.columns.length &&
    query.returnsColumns.every((c) => table.columns.some((tc) => tc.name === c))
  ) {
    return typeName;
  }

  // Partial return — generate a Pick type
  const cols = query.returnsColumns.map((c) => `"${c}"`).join(" | ");
  return `Pick<${typeName}, ${cols}>`;
}

function generateReturnType(query: QueryDef, resultType: string | null): string {
  switch (query.command) {
    case "one":
      return `Promise<${resultType ?? "unknown"} | null>`;
    case "many":
      return `Promise<${resultType ?? "unknown"}[]>`;
    case "exec":
      return "Promise<void>";
    case "execrows":
      return "Promise<number>";
    case "execresult":
      return "Promise<QueryResult>";
    default:
      return "Promise<void>";
  }
}

function generateFunctionBody(query: QueryDef): string {
  const paramArgs = query.params.map((p) => `params.${p.name}`).join(", ");
  const queryArgs = query.params.length > 0
    ? `sql, [${paramArgs}]`
    : "sql";

  switch (query.command) {
    case "one":
      return `  const result = await client.query(${queryArgs});\n  return result.rows[0] ?? null;`;
    case "many":
      return `  const result = await client.query(${queryArgs});\n  return result.rows;`;
    case "exec":
      return `  await client.query(${queryArgs});`;
    case "execrows":
      return `  const result = await client.query(${queryArgs});\n  return result.rowCount ?? 0;`;
    case "execresult":
      return `  return await client.query(${queryArgs});`;
    default:
      return `  await client.query(${queryArgs});`;
  }
}

function generateFunction(query: QueryDef, snapshot: SchemaSnapshot): string {
  const fnName = camelCase(query.name);
  const resultType = generateResultType(query, snapshot);
  const returnType = generateReturnType(query, resultType);

  const hasParams = query.params.length > 0;
  const paramsType = hasParams ? `${pascalCase(query.name)}Params` : null;

  const args = hasParams
    ? `client: Client | Pool, params: ${paramsType}`
    : "client: Client | Pool";

  const sql = query.sql.replace(/'/g, "\\'").replace(/\n/g, "\\n");

  const lines: string[] = [];
  lines.push(`export async function ${fnName}(${args}): ${returnType} {`);
  lines.push(`  const sql = '${sql}';`);
  lines.push(generateFunctionBody(query));
  lines.push("}");

  return lines.join("\n");
}

export function generateQueryFiles(
  queries: QueryDef[],
  snapshot: SchemaSnapshot,
): Record<string, string> {
  // Group queries by source file
  const grouped = new Map<string, QueryDef[]>();
  for (const query of queries) {
    const key = query.sourceFile.replace(/\.sql$/, "");
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(query);
  }

  const files: Record<string, string> = {};

  for (const [basename, fileQueries] of grouped) {
    const lines: string[] = [
      "// This file is auto-generated by tsqx. Do not edit manually.",
      'import type { Client, Pool, QueryResult } from "pg";',
    ];

    // Collect table type imports
    const tableImports = new Set<string>();
    for (const query of fileQueries) {
      if (query.returnsTable && snapshot[query.returnsTable]) {
        tableImports.add(query.returnsTable);
      }
    }
    if (tableImports.size > 0) {
      const imports = [...tableImports]
        .map((t) => `type ${pascalCase(t)}`)
        .join(", ");
      lines.push(`import { ${imports} } from "../../generated";`);
    }

    lines.push("");

    for (const query of fileQueries) {
      // Param interface
      const paramInterface = generateParamInterface(query);
      if (paramInterface) {
        lines.push(paramInterface);
        lines.push("");
      }

      // Param JSON Schema
      const paramSchema = generateParamSchema(query);
      if (paramSchema) {
        lines.push(paramSchema);
        lines.push("");
      }

      // Function
      lines.push(generateFunction(query, snapshot));
      lines.push("");
    }

    files[`${basename}.ts`] = lines.join("\n");
  }

  return files;
}
