import type { Dialect } from "../dialect";
import type { SchemaSnapshot, TableDef, ColumnDef } from "./types";

function pascalCase(str: string): string {
  return str
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function tableToJsonSchema(
  table: TableDef,
  dialect: Dialect,
): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const col of table.columns) {
    const jsonType = dialect.sqlTypeToJsonSchema(col.type);

    if (col.nullable) {
      properties[col.name] = {
        ...jsonType,
        type: Array.isArray(jsonType.type)
          ? [...jsonType.type, "null"]
          : [jsonType.type, "null"],
      };
    } else {
      properties[col.name] = jsonType;
      required.push(col.name);
    }
  }

  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: pascalCase(table.name),
    type: "object",
    properties,
    required,
    additionalProperties: false,
  };
}

export function generateJsonSchemas(
  snapshot: SchemaSnapshot,
  dialect: Dialect,
): Record<string, Record<string, unknown>> {
  const schemas: Record<string, Record<string, unknown>> = {};

  for (const [name, table] of Object.entries(snapshot)) {
    schemas[name] = tableToJsonSchema(table, dialect);
  }

  return schemas;
}

function columnToTsType(col: ColumnDef, dialect: Dialect): string {
  const base = dialect.sqlTypeToTsType(col.type);
  return col.nullable ? `${base} | null` : base;
}

export function generateTypeScript(
  snapshot: SchemaSnapshot,
  dialect: Dialect,
): string {
  const lines: string[] = [
    "// This file is auto-generated by tsqx. Do not edit manually.",
    "",
  ];

  for (const table of Object.values(snapshot)) {
    const typeName = pascalCase(table.name);

    lines.push(`export interface ${typeName} {`);
    for (const col of table.columns) {
      lines.push(`  ${col.name}: ${columnToTsType(col, dialect)};`);
    }
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}
