import type { Dialect } from "../dialect";
import type { SchemaSnapshot, TableDef, ColumnDef } from "./types";
import { pascalCase } from "../utils";

function tableToJsonSchema(
  table: TableDef,
  dialect: Dialect,
): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const col of table.columns) {
    const jsonType = dialect.sqlTypeToJsonSchema(col.type);

    if (col.nullable) {
      properties[col.name] = {
        ...jsonType,
        type: Array.isArray(jsonType.type)
          ? [...jsonType.type, "null"]
          : [jsonType.type, "null"],
      };
    } else {
      properties[col.name] = jsonType;
      required.push(col.name);
    }
  }

  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: pascalCase(table.name),
    type: "object",
    properties,
    required,
    additionalProperties: false,
  };
}

function columnToTsType(col: ColumnDef, dialect: Dialect): string {
  const base = dialect.sqlTypeToTsType(col.type);
  return col.nullable ? `${base} | null` : base;
}

export function generateTableFile(
  table: TableDef,
  dialect: Dialect,
): string {
  const typeName = pascalCase(table.name);
  const jsonSchema = tableToJsonSchema(table, dialect);

  const lines: string[] = [
    "// This file is auto-generated by tsqx. Do not edit manually.",
    "",
    `export interface ${typeName} {`,
  ];

  for (const col of table.columns) {
    lines.push(`  ${col.name}: ${columnToTsType(col, dialect)};`);
  }

  lines.push("}");
  lines.push("");
  lines.push(`export const ${typeName}Schema = ${JSON.stringify(jsonSchema, null, 2)} as const;`);
  lines.push("");

  return lines.join("\n");
}

export function generateSchemaFiles(
  snapshot: SchemaSnapshot,
  dialect: Dialect,
): Record<string, string> {
  const files: Record<string, string> = {};

  for (const [name, table] of Object.entries(snapshot)) {
    files[`${name}.ts`] = generateTableFile(table, dialect);
  }

  // Generate barrel file
  const indexLines: string[] = [
    "// This file is auto-generated by tsqx. Do not edit manually.",
    "",
  ];
  for (const name of Object.keys(snapshot)) {
    const typeName = pascalCase(name);
    indexLines.push(`export { type ${typeName}, ${typeName}Schema } from "./${name}";`);
  }
  indexLines.push("");

  files["index.ts"] = indexLines.join("\n");

  return files;
}
