CREATE TABLE traces (
  id UUID PRIMARY KEY,
  traceId VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255),
  sessionId VARCHAR(255),
  userId VARCHAR(255),
  status VARCHAR(10) NOT NULL DEFAULT 'unset',
  startTime TIMESTAMP NOT NULL,
  endTime TIMESTAMP,
  durationMs INTEGER,
  spanCount INTEGER NOT NULL DEFAULT 0,
  totalInputTokens INTEGER NOT NULL DEFAULT 0,
  totalOutputTokens INTEGER NOT NULL DEFAULT 0,
  totalTokens INTEGER NOT NULL DEFAULT 0,
  totalCost INTEGER NOT NULL DEFAULT 0,
  tags JSONB NOT NULL DEFAULT '{}',
  metadata JSONB NOT NULL DEFAULT '{}',
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE spans (
  id UUID PRIMARY KEY,
  traceId VARCHAR(255) NOT NULL REFERENCES traces(traceId),
  spanId VARCHAR(255) NOT NULL UNIQUE,
  parentSpanId VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  kind INTEGER NOT NULL DEFAULT 1,
  status INTEGER NOT NULL DEFAULT 0,
  statusMessage TEXT,
  startTime TIMESTAMP NOT NULL,
  endTime TIMESTAMP,
  durationMs INTEGER,
  provider VARCHAR(255),
  model VARCHAR(255),
  promptTokens INTEGER NOT NULL DEFAULT 0,
  completionTokens INTEGER NOT NULL DEFAULT 0,
  totalTokens INTEGER NOT NULL DEFAULT 0,
  cost INTEGER NOT NULL DEFAULT 0,
  source VARCHAR(50) NOT NULL DEFAULT 'gateway',
  input JSONB,
  output JSONB,
  attributes JSONB NOT NULL DEFAULT '{}',
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE span_events (
  id UUID PRIMARY KEY,
  traceId VARCHAR(255) NOT NULL,
  spanId VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  attributes JSONB NOT NULL DEFAULT '{}',
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);
